#!/bin/bash
#
# This script is licensed under the BSD-2-Clause license:
#
# -----//-----
#
# Copyright (c) 2012, Martin Erik Werner <martinerikwerner@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# -----//-----
#
# This script extracts the three sprite canvases contained within LIERO.CHR,
# and dumps them as greyscale images in xpm format, use the 'packgfx' script to
# pack them back up again

gfxfile="$1"
headersize1=10
headersize2=4
headersize3=4
imgsize1=$((16 * 1760))
imgsize2=$((7 * 910))
imgsize3=$((4 * 120))
imgoffset1="$headersize1"
imgoffset2="$(($headersize1 + $imgsize1 + $headersize2))"
imgoffset3="$(($headersize1 + $imgsize1 + $headersize2 + $imgsize2 + \
	$headersize3))"
imgdim1=16x1760
imgdim2=7x910
imgdim3=4x120

dd if="$gfxfile" bs=1 ibs=1 skip="$imgoffset1" count="$imgsize1" | \
	convert -depth 8 -size "$imgdim1" gray:- gfx1.xpm
dd if="$gfxfile" bs=1 ibs=1 skip="$imgoffset2" count="$imgsize2" | \
	convert -depth 8 -size "$imgdim2" gray:- gfx2.xpm
dd if="$gfxfile" bs=1 ibs=1 skip="$imgoffset3" count="$imgsize3" | \
	convert -depth 8 -size "$imgdim3" gray:- gfx3.xpm
